### ISSUE TITLE
Failed to open TCP connection to sns (getaddrinfo: No address associated with hostname)

### ISSUE THREAD

**Issue by yanc0** [SimpleFinance/sensu-transport-snssqs#11]
Hello,

Friday at nearly same time, on of my sensu-client and my sensu-server crashed with this stacktrace

```
/opt/sensu/embedded/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect': Failed to open TCP connection to sns.eu-west-1.amazonaws.com:443 (getaddrinfo: No address associated with hostname) (Seahorse::Client::NetworkingError)
    from /opt/sensu/embedded/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
    from /opt/sensu/embedded/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
    from /opt/sensu/embedded/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
    from /opt/sensu/embedded/lib/ruby/2.3.0/net/http.rb:878:in `connect'
    from /opt/sensu/embedded/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
    from /opt/sensu/embedded/lib/ruby/2.3.0/net/http.rb:858:in `start'
    from /opt/sensu/embedded/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/seahorse/client/net_http/connection_pool.rb:281:in `start_session'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/seahorse/client/net_http/connection_pool.rb:93:in `session_for'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/seahorse/client/net_http/handler.rb:116:in `session'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/seahorse/client/net_http/handler.rb:68:in `transmit'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/seahorse/client/net_http/handler.rb:42:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/seahorse/client/plugins/content_length.rb:12:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/plugins/request_signer.rb:84:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/plugins/retry_errors.rb:87:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/plugins/retry_errors.rb:118:in `retry_request'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/plugins/retry_errors.rb:101:in `retry_if_possible'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/plugins/retry_errors.rb:89:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/plugins/retry_errors.rb:118:in `retry_request'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/plugins/retry_errors.rb:101:in `retry_if_possible'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/plugins/retry_errors.rb:89:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/plugins/retry_errors.rb:118:in `retry_request'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/plugins/retry_errors.rb:101:in `retry_if_possible'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/plugins/retry_errors.rb:89:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/query/handler.rb:27:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/seahorse/client/plugins/response_target.rb:21:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/seahorse/client/request.rb:70:in `send_request'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.7/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.4/lib/sensu/transport/snssqs.rb:155:in `send_message'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.4/lib/sensu/transport/snssqs.rb:138:in `block in publish'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1076:in `block in spawn_threadpool'

```

Maybe this was due to the Dyn DDos, I don't know but, I think it have to retry connecting continuously instead of crashing. Is there a solution available or do I have to monitor my monitoring agents processes? Maybe this is a sensu-core question too.

Thanks

**Comment by tomwans** [comment]
Is it working now? This seemed like an issue with your DNS system, not sensu-transport-snssqs.

**Comment by yanc0** [comment]
Hi,

I think the issue is not the temporary connectivity error but the sensu-server crashing instead of retrying.
Here an other error from yesterday:

```
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.5/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': We encountered an internal error.
 Please try again. (Aws::SQS::Errors::InternalError)                                                                                                                
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'                               
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.5/lib/seahorse/client/plugins/response_target.rb:21:in `call'                            
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.5/lib/seahorse/client/request.rb:70:in `send_request'                                    
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.5/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'      
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.4/lib/sensu/transport/snssqs.rb:117:in `block in acknowledge'                  
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1076:in `block in spawn_threadpool'                              
```

Do I have to post this issue in sensu-core repo?

**Comment by runningman84** [comment]
This transport should do a similar reconnect procedure like the rabbitmq transport. I am not sure if this is implemented in the transport or core? @cwj or @portertech can you advice?
