### ISSUE TITLE
gem issue

### ISSUE THREAD

**Issue by runningman84** [SimpleFinance/sensu-transport-snssqs#2]
I have tried to install the gem with chef

```
sensu_gem 'sensu-transport-snssqs' do
  action :install
end
```

But I cannot find the snssqs.rb anywhere in /opt/sensu:

```
ubuntu@ip-172-31-5-200:/opt/sensu$ find . | grep snssqs
./embedded/lib/ruby/gems/2.3.0/cache/sensu-transport-snssqs-1.0.gem
./embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-1.0
./embedded/lib/ruby/gems/2.3.0/specifications/sensu-transport-snssqs-1.0.gemspec
```

Sensu does not find the transport either. A manual download and placement of the file here /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-6.0.0/lib/sensu/transport/snssqs.rb
did work.

The statsd dependency was also not solved automatically.

**Comment by runningman84** [comment]
It looks like the package published at rubygems.org are outdated. Can somebody please release an updated version?

**Comment by tomwans** [comment]
I've uploaded the latest version, dubbed it 2.0 — https://rubygems.org/gems/sensu-transport-snssqs/versions/2.0.

Let me know if that doesn't work. Thanks!

**Comment by runningman84** [comment]
@tomwans the 2.0 still does not contain the snssqs.rb file? Where is it supposed to be installed?

**Comment by tomwans** [comment]
oops, my bad.

let's try this again: https://rubygems.org/gems/sensu-transport-snssqs/versions/2.0.1 ?

**Comment by runningman84** [comment]
The gem file contains the transport file, but is does not work with sensu-client 0.25.3:

```
{"timestamp":"2016-07-01T06:43:22.827803+0000","level":"warn","message":"loading config file","file":"/etc/sensu/config.json"}
{"timestamp":"2016-07-01T06:43:22.827893+0000","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d"}
{"timestamp":"2016-07-01T06:43:22.827931+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/ec2_node.json"}
{"timestamp":"2016-07-01T06:43:22.827979+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/ec2_node.json","changes":{"ec2_node":[null,{"ec2_states":["terminated","stopping","shutting-down","stopped"]}]}}
{"timestamp":"2016-07-01T06:43:22.828017+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/snssqs.json"}
{"timestamp":"2016-07-01T06:43:22.828071+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/snssqs.json","changes":{"snssqs":[null,{"max_number_of_messages":10,"wait_time_seconds":2,"region":"eu-central-1","consuming_sqs_queue_url":"https://sqs.eu-central-1.amazonaws.com/001579709704/sensu-server","publishing_sns_topic_arn":"arn:aws:sns:eu-central-1:001579709704:sensu-client-1","statsd_addr":"localhost:8125","statsd_namespace":"snssqs","statsd_sample_rate":1}]}}
{"timestamp":"2016-07-01T06:43:22.828113+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks/disk_usage_metrics.json"}
{"timestamp":"2016-07-01T06:43:22.828167+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/checks/disk_usage_metrics.json","changes":{"checks":{"disk_usage_metrics":[null,{"type":"metric","command":"metrics-disk-usage.rb -l --scheme :::scheme_prefix::::::name:::.disk_usage","standalone":true,"handlers":["metrics"],"interval":60,"occurrences":2}]}}}
{"timestamp":"2016-07-01T06:43:22.828230+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks/fs_writeable_tmp.json"}
{"timestamp":"2016-07-01T06:43:22.828281+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/checks/fs_writeable_tmp.json","changes":{"checks":{"fs_writeable_tmp":[null,{"command":"check-fs-writable.rb -d /tmp","standalone":true,"handlers":["default"],"interval":60,"occurrences":5}]}}}
{"timestamp":"2016-07-01T06:43:22.828316+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks/load_metrics.json"}
{"timestamp":"2016-07-01T06:43:22.828367+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/checks/load_metrics.json","changes":{"checks":{"load_metrics":[null,{"type":"metric","command":"metrics-load.rb --scheme :::scheme_prefix::::::name:::.load","standalone":true,"handlers":["metrics"],"interval":60,"occurrences":2}]}}}
{"timestamp":"2016-07-01T06:43:22.828406+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks/memory_metrics.json"}
{"timestamp":"2016-07-01T06:43:22.828459+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/checks/memory_metrics.json","changes":{"checks":{"memory_metrics":[null,{"type":"metric","command":"metrics-memory.rb --scheme :::scheme_prefix::::::name:::.memory","standalone":true,"handlers":["metrics"],"interval":60,"occurrences":2}]}}}
{"timestamp":"2016-07-01T06:43:22.828494+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks/ssh.json"}
{"timestamp":"2016-07-01T06:43:22.828543+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/checks/ssh.json","changes":{"checks":{"ssh":[null,{"command":"check-banner.rb","standalone":true,"handlers":["default"],"interval":60,"occurrences":5}]}}}
{"timestamp":"2016-07-01T06:43:22.828580+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks/swap.json"}
{"timestamp":"2016-07-01T06:43:22.828631+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/checks/swap.json","changes":{"checks":{"swap":[null,{"command":"check-swap.rb -w 60 -c 50","standalone":true,"handlers":["default"],"interval":60,"occurrences":5}]}}}
{"timestamp":"2016-07-01T06:43:22.828672+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks/memory.json"}
{"timestamp":"2016-07-01T06:43:22.828750+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/checks/memory.json","changes":{"checks":{"memory":[null,{"command":"check-memory.rb -w 15 -c 10","standalone":true,"handlers":["default"],"interval":60,"occurrences":5}]}}}
{"timestamp":"2016-07-01T06:43:22.828785+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks/load.json"}
{"timestamp":"2016-07-01T06:43:22.828835+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/checks/load.json","changes":{"checks":{"load":[null,{"command":"check-load.rb -p -w 3,2,1 -c 9,6,3","standalone":true,"handlers":["default"],"interval":60,"occurrences":5}]}}}
{"timestamp":"2016-07-01T06:43:22.828868+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks/disk_usage.json"}
{"timestamp":"2016-07-01T06:43:22.828918+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/checks/disk_usage.json","changes":{"checks":{"disk_usage":[null,{"command":"check-disk-usage.rb -w 80 -c 90 -x nfs,tmpfs,fuse","standalone":true,"handlers":["default"],"interval":60,"occurrences":5}]}}}
{"timestamp":"2016-07-01T06:43:22.828955+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks/interface_metrics.json"}
{"timestamp":"2016-07-01T06:43:22.829007+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/checks/interface_metrics.json","changes":{"checks":{"interface_metrics":[null,{"type":"metric","command":"metrics-interface.rb --scheme :::scheme_prefix::::::name:::.interface","standalone":true,"handlers":["metrics"],"interval":60,"occurrences":2}]}}}
{"timestamp":"2016-07-01T06:43:22.829043+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks/cpu_metrics.json"}
{"timestamp":"2016-07-01T06:43:22.829098+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/checks/cpu_metrics.json","changes":{"checks":{"cpu_metrics":[null,{"type":"metric","command":"metrics-cpu.rb --scheme :::scheme_prefix::::::name:::.cpu","standalone":true,"handlers":["metrics"],"interval":60,"occurrences":2}]}}}
{"timestamp":"2016-07-01T06:43:22.829139+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/checks/disk_metrics.json"}
{"timestamp":"2016-07-01T06:43:22.829191+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/checks/disk_metrics.json","changes":{"checks":{"disk_metrics":[null,{"type":"metric","command":"metrics-disk.rb --scheme :::scheme_prefix::::::name:::.disk","standalone":true,"handlers":["metrics"],"interval":60,"occurrences":2}]}}}
{"timestamp":"2016-07-01T06:43:22.829225+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/filters/occurrences.json"}
{"timestamp":"2016-07-01T06:43:22.829299+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/filters/occurrences.json","changes":{"filters":{"occurrences":[null,{"attributes":{"occurrences":"eval: value > :::check.occurrences|10:::"}}]}}}
{"timestamp":"2016-07-01T06:43:22.829333+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/filters/keepalives.json"}
{"timestamp":"2016-07-01T06:43:22.829387+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/filters/keepalives.json","changes":{"filters":{"keepalives":[null,{"attributes":{"check":{"name":"keepalive","status":2},"occurrences":"eval: value > 2"}}]}}}
{"timestamp":"2016-07-01T06:43:22.829421+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/filters/chef_env_prod.json"}
{"timestamp":"2016-07-01T06:43:22.829472+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/filters/chef_env_prod.json","changes":{"filters":{"chef_env_prod":[null,{"attributes":{"client":{"chef_env":"prod"}}}]}}}
{"timestamp":"2016-07-01T06:43:22.829512+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/filters/ec2.json"}
{"timestamp":"2016-07-01T06:43:22.829563+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/filters/ec2.json","changes":{"filters":{"ec2":[null,{"attributes":{"client":{"cloud_provider":"ec2"}}}]}}}
{"timestamp":"2016-07-01T06:43:22.829599+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/filters/actions.json"}
{"timestamp":"2016-07-01T06:43:22.829647+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/filters/actions.json","changes":{"filters":{"actions":[null,{"attributes":{"action":"eval: %w[create resolve].include? value.to_s"}}]}}}
{"timestamp":"2016-07-01T06:43:22.829680+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/filters/chef.json"}
{"timestamp":"2016-07-01T06:43:22.829732+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/filters/chef.json","changes":{"filters":{"chef":[null,{"attributes":{"client":{"chef_env":"eval: value.length > 0"}}}]}}}
{"timestamp":"2016-07-01T06:43:22.829802+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/handlers/ec2_node.json"}
{"timestamp":"2016-07-01T06:43:22.829857+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/handlers/ec2_node.json","changes":{"handlers":{"ec2_node":[null,{"type":"pipe","filters":["keepalives","ec2"],"severities":["warning","critical"],"command":"handler-ec2_node-custom.rb","timeout":300}]}}}
{"timestamp":"2016-07-01T06:43:22.829891+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/handlers/metrics.json"}
{"timestamp":"2016-07-01T06:43:22.829937+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/handlers/metrics.json","changes":{"handlers":{"metrics":[null,{"type":"set","handlers":["relay"]}]}}}
{"timestamp":"2016-07-01T06:43:22.829969+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/handlers/default.json"}
{"timestamp":"2016-07-01T06:43:22.830051+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/handlers/default.json","changes":{"handlers":{"default":[null,{"type":"set","handlers":["remedy","chef_node","ec2_node"]}]}}}
{"timestamp":"2016-07-01T06:43:22.830096+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/handlers/maintenance.json"}
{"timestamp":"2016-07-01T06:43:22.830146+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/handlers/maintenance.json","changes":{"handlers":{"maintenance":[null,{"type":"pipe","command":"handler-sensu-maintenance-custom.rb","timeout":300}]}}}
{"timestamp":"2016-07-01T06:43:22.830182+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/handlers/chef_node.json"}
{"timestamp":"2016-07-01T06:43:22.830241+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/handlers/chef_node.json","changes":{"handlers":{"chef_node":[null,{"type":"pipe","filters":["keepalives","chef"],"severities":["warning","critical"],"command":"sudo handler-chef-node.rb","timeout":300}]}}}
{"timestamp":"2016-07-01T06:43:22.830278+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/handlers/deregister.json"}
{"timestamp":"2016-07-01T06:43:22.830356+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/handlers/deregister.json","changes":{"handlers":{"deregister":[null,{"type":"pipe","command":"handler-sensu-deregister.rb","timeout":300}]}}}
{"timestamp":"2016-07-01T06:43:22.830391+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/chef.json"}
{"timestamp":"2016-07-01T06:43:22.830437+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/chef.json","changes":{"chef":[null,{"server_url":"chefzero://localhost:8889","client_name":"server1-ubuntu-1404","client_key":"/tmp/kitchen/client.pem","verify_ssl":false}]}}
{"timestamp":"2016-07-01T06:43:22.830532+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/client.json"}
{"timestamp":"2016-07-01T06:43:22.830608+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/client.json","changes":{"client":[null,{"address":"52.29.151.122","subscriptions":["region:eu-central-1","provider:ec2","env:_default","os:linux","all"],"name":"server1-ubuntu-1404","remedy_app":"Sensu Monitoring","remedy_group":"internet_services","ec2_ami_id":"ami-09618e66","ec2_instance_id":"i-0965ef12bea8254cc","ec2_instance_type":"t2.small","ec2_av_zone":"eu-central-1b","ec2_profile":"default-hvm","ec2_region":"eu-central-1","cloud_local_ipv4":"172.31.10.156","cloud_public_ipv4":"52.29.151.122","cloud_provider":"ec2","platform":"ubuntu","platform_version":"14.04","platform_family":"debian","chef_env":"_default","scheme_prefix":"sensu.sensu.eu-central-1b."}]}}
{"timestamp":"2016-07-01T06:43:22.836986+0000","level":"warn","message":"loading extension files from directory","directory":"/etc/sensu/extensions/client"}
{"timestamp":"2016-07-01T06:43:22.837355+0000","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
{"timestamp":"2016-07-01T06:43:23.086994+0000","level":"info","message":"subscribing to type=fanout, pipe=region:eu-central-1, funnel=server1-ubuntu-1404-0.25.3-1467355402"}
{"timestamp":"2016-07-01T06:43:23.087083+0000","level":"info","message":"subscribing to type=fanout, pipe=provider:ec2, funnel=server1-ubuntu-1404-0.25.3-1467355402"}
{"timestamp":"2016-07-01T06:43:23.087124+0000","level":"info","message":"subscribing to type=fanout, pipe=env:_default, funnel=server1-ubuntu-1404-0.25.3-1467355402"}
{"timestamp":"2016-07-01T06:43:23.087158+0000","level":"info","message":"subscribing to type=fanout, pipe=os:linux, funnel=server1-ubuntu-1404-0.25.3-1467355402"}
{"timestamp":"2016-07-01T06:43:23.087240+0000","level":"info","message":"subscribing to type=fanout, pipe=all, funnel=server1-ubuntu-1404-0.25.3-1467355402"}
{"timestamp":"2016-07-01T06:43:27.489973+0000","level":"info","message":"publishing check result","payload":{"client":"server1-ubuntu-1404","check":{"type":"metric","command":"metrics-cpu.rb --scheme :::scheme_prefix::::::name:::.cpu","standalone":true,"handlers":["metrics"],"interval":60,"occurrences":2,"name":"cpu_metrics","issued":1467355407,"executed":1467355407,"duration":0.132,"output":"sensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.total.user 11188 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.total.nice 163 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.total.system 1984 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.total.idle 22792 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.total.iowait 15346 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.total.irq 0 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.total.softirq 13 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.total.steal 627 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.total.guest 0 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.total. 0 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.cpu0.user 11188 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.cpu0.nice 163 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.cpu0.system 1984 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.cpu0.idle 22792 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.cpu0.iowait 15346 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.cpu0.irq 0 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.cpu0.softirq 13 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.cpu0.steal 627 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.cpu0.guest 0 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.cpu0. 0 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.intr 0 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.ctxt 522077 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.btime 1467354890 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.processes 19050 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.procs_running 1 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.procs_blocked 0 1467355407\nsensu.sensu.eu-central-1b.server1-ubuntu-1404.cpu.cpu_count 1 1467355407\n","status":0}}}
{"timestamp":"2016-07-01T06:43:30.343655+0000","level":"info","message":"received check request","check":{"client":"server1-ubuntu-1404","check":{"thresholds":{"warning":120,"critical":180},"name":"keepalive","issued":1467355410,"executed":1467355410,"output":"No keepalive sent from client for 42631 seconds (>=180)","status":2},"signature":""}}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:184:in `definition_exists?': undefined method `to_sym' for nil:NilClass (NoMethodError)
Did you mean?  to_s
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:62:in `block (2 levels) in create_category_methods'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:211:in `process_check_request'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:273:in `block (2 levels) in setup_subscriptions'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.1/lib/sensu/transport/snssqs.rb:95:in `block (3 levels) in subscribe'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.1/lib/sensu/transport/snssqs.rb:59:in `statsd_time'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.1/lib/sensu/transport/snssqs.rb:91:in `block (2 levels) in subscribe'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/iterator.rb:138:in `block in each'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/iterator.rb:231:in `block in spawn_workers'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `times'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `run_deferred_callbacks'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:18:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/exe/sensu-client:10:in `<top (required)>'
    from /opt/sensu/bin/sensu-client:22:in `load'
    from /opt/sensu/bin/sensu-client:22:in `<main>'
```

The server log looks fine so far.

**Comment by runningman84** [comment]
Btw. this problem even occurs using a single client without any check. The client works for a few seconds and then crashes with the error above.

I wonder how does the client receive a check request? My assumption was that the client could not receive anything from the server using snssqs?

**Comment by tomwans** [comment]
@runningman84 — that does look like a very strange bug. Can you try with Sensu 0.25.0? That is the version we are using today and it's been working fine for us.

**Comment by tomwans** [comment]
> I wonder how does the client receive a check request? My assumption was that the client could not receive anything from the server using snssqs?

That's correct. However, the client will try to subscribe if there are non-standalone checks to be run. Maybe one of the checks are not in pure standalone mode?

**Comment by runningman84** [comment]
All of my checks are standalone. The problem also happens with 0.25.

I have now commented out everything in the statsd_incr and statsd_time methods. The client seems to stay alive now.
