### ISSUE TITLE
Client receives checks from sqs queue

### ISSUE THREAD

**Issue by runningman84** [SimpleFinance/sensu-transport-snssqs#5]
My assumption was that the client does not need to have access to the sqs queue. Any client should just send everything to sns which is connected to sqs. The sqs queue itself is pulled by all sensu servers.

But the actual result looks different. Even a client receives messages from the sqs que. 

Funny enough you need to configure server specific settings like wait_time_seconds, max_number_of_messages, consuming_sqs_queue_url in the client otherweise you get errors like this

```
{"timestamp":"2016-07-07T12:16:05.475283+0000","level":"debug","message":"connecting to transport","name":"snssqs","settings":{"publishing_sns_topic_arn":"arn:aws:sns:eu-central-1:001579709704:sensu-client-1"}}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/aws-sdk-core/endpoint_provider.rb:67:in `block in partition_matching_region': undefined method `match' for nil:NilClass (NoMethodError)
Did you mean?  catch
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/aws-sdk-core/endpoint_provider.rb:66:in `each'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/aws-sdk-core/endpoint_provider.rb:66:in `find'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/aws-sdk-core/endpoint_provider.rb:66:in `partition_matching_region'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/aws-sdk-core/endpoint_provider.rb:55:in `get_partition'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/aws-sdk-core/endpoint_provider.rb:26:in `endpoint_for'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/aws-sdk-core/endpoint_provider.rb:10:in `resolve'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/aws-sdk-core/endpoint_provider.rb:80:in `resolve'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/aws-sdk-core/plugins/regional_endpoint.rb:24:in `block in <class:RegionalEndpoint>'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/configuration.rb:70:in `call'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/configuration.rb:205:in `block in resolve_defaults'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/configuration.rb:57:in `each'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/configuration.rb:57:in `each'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/configuration.rb:204:in `resolve_defaults'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/configuration.rb:200:in `value_at'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/configuration.rb:189:in `block in resolve'
    from /opt/sensu/embedded/lib/ruby/2.3.0/set.rb:306:in `each_key'
    from /opt/sensu/embedded/lib/ruby/2.3.0/set.rb:306:in `each'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/configuration.rb:189:in `resolve'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/configuration.rb:177:in `apply_defaults'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/configuration.rb:150:in `build!'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/base.rb:68:in `build_config'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/base.rb:19:in `initialize'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.3.20/lib/seahorse/client/base.rb:105:in `new'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.2/lib/sensu/transport/snssqs.rb:37:in `connect'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-6.0.0/lib/sensu/transport.rb:24:in `connect'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/daemon.rb:250:in `setup_transport'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:435:in `start'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:19:in `block in run'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:18:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/exe/sensu-client:10:in `<top (required)>'
    from /opt/sensu/bin/sensu-client:22:in `load'
    from /opt/sensu/bin/sensu-client:22:in `<main>'
```

These clients runs (containing the full snssqs config) show that the client receives messages from the queue:

```
# client run 1
rm /var/log/sens/sensu-client.log
/etc/init.d/sensu-client start

{"timestamp":"2016-07-07T12:06:40.064390+0000","level":"warn","message":"loading config file","file":"/etc/sensu/config.json"}
{"timestamp":"2016-07-07T12:06:40.064491+0000","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d"}
{"timestamp":"2016-07-07T12:06:40.064529+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/snssqs.json"}
{"timestamp":"2016-07-07T12:06:40.064580+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/snssqs.json","changes":{"snssqs":[null,{"max_number_of_messages":10,"wait_time_seconds":2,"region":"eu-central-1","consuming_sqs_queue_url":"https://sqs.eu-central-1.amazonaws.com/001579709704/sensu-server","publishing_sns_topic_arn":"arn:aws:sns:eu-central-1:001579709704:sensu-client-1"}]}}
{"timestamp":"2016-07-07T12:06:40.064623+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/client.json"}
{"timestamp":"2016-07-07T12:06:40.064727+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/client.json","changes":{"client":[null,{"address":"52.59.48.159","subscriptions":["region:eu-central-1","provider:ec2","env:_default","os:linux","all"],"name":"client1-ubuntu-1404","signature":"f8022acc4947b319f27abb4216d16243","keepalive":{"thresholds":{"warning":180,"critical":600}},"ec2":{"ami_id":"ami-09618e66","instance_id":"i-0206a4235b6010ea8","instance_type":"t2.small","az":"eu-central-1b","profile":"default-hvm","region":"eu-central-1","tags":{"name":"user_test"}},"cloud":{"local_ipv4":"172.31.1.247","public_ipv4":"52.59.48.159","provider":"ec2"},"platform":"ubuntu","platform_version":"14.04","platform_family":"debian","chef":{"endpoint":"chefzero://localhost:8889","environment":"_default","client":"client1-ubuntu-1404","key":"/tmp/kitchen/client.pem"},"scheme_prefix":"sensu.default."}]}}
{"timestamp":"2016-07-07T12:06:40.071895+0000","level":"warn","message":"loading extension files from directory","directory":"/etc/sensu/extensions"}
{"timestamp":"2016-07-07T12:06:40.072111+0000","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
{"timestamp":"2016-07-07T12:06:40.072163+0000","level":"debug","message":"setting eventmachine threadpool size","size":22}
{"timestamp":"2016-07-07T12:06:40.094415+0000","level":"debug","message":"connecting to transport","name":"snssqs","settings":{"max_number_of_messages":10,"wait_time_seconds":2,"region":"eu-central-1","consuming_sqs_queue_url":"https://sqs.eu-central-1.amazonaws.com/001579709704/sensu-server","publishing_sns_topic_arn":"arn:aws:sns:eu-central-1:001579709704:sensu-client-1"}}
{"timestamp":"2016-07-07T12:06:40.320795+0000","level":"debug","message":"binding client tcp and udp sockets","options":{"bind":"127.0.0.1","port":3030}}
{"timestamp":"2016-07-07T12:06:40.321067+0000","level":"debug","message":"scheduling keepalives"}
{"timestamp":"2016-07-07T12:06:40.321233+0000","level":"debug","message":"publishing keepalive","payload":{"address":"52.59.48.159","subscriptions":["region:eu-central-1","provider:ec2","env:_default","os:linux","all"],"name":"client1-ubuntu-1404","signature":"f8022acc4947b319f27abb4216d16243","keepalive":{"thresholds":{"warning":180,"critical":600}},"ec2":{"ami_id":"ami-09618e66","instance_id":"i-0206a4235b6010ea8","instance_type":"t2.small","az":"eu-central-1b","profile":"default-hvm","region":"eu-central-1","tags":{"name":"user_test"}},"cloud":{"local_ipv4":"172.31.1.247","public_ipv4":"52.59.48.159","provider":"ec2"},"platform":"ubuntu","platform_version":"14.04","platform_family":"debian","chef":{"endpoint":"chefzero://localhost:8889","environment":"_default","client":"client1-ubuntu-1404","key":"/tmp/kitchen/client.pem"},"scheme_prefix":"sensu.default.","version":"0.25.3","timestamp":1467893200}}
{"timestamp":"2016-07-07T12:06:40.326841+0000","level":"debug","message":"subscribing to client subscriptions"}
{"timestamp":"2016-07-07T12:06:40.326881+0000","level":"debug","message":"subscribing to a subscription","subscription":"region:eu-central-1"}
{"timestamp":"2016-07-07T12:06:40.326927+0000","level":"info","message":"subscribing to type=fanout, pipe=region:eu-central-1, funnel=client1-ubuntu-1404-0.25.3-1467893200"}
{"timestamp":"2016-07-07T12:06:40.326967+0000","level":"debug","message":"subscribing to a subscription","subscription":"provider:ec2"}
{"timestamp":"2016-07-07T12:06:40.326999+0000","level":"info","message":"subscribing to type=fanout, pipe=provider:ec2, funnel=client1-ubuntu-1404-0.25.3-1467893200"}
{"timestamp":"2016-07-07T12:06:40.327021+0000","level":"debug","message":"subscribing to a subscription","subscription":"env:_default"}
{"timestamp":"2016-07-07T12:06:40.327048+0000","level":"info","message":"subscribing to type=fanout, pipe=env:_default, funnel=client1-ubuntu-1404-0.25.3-1467893200"}
{"timestamp":"2016-07-07T12:06:40.327068+0000","level":"debug","message":"subscribing to a subscription","subscription":"os:linux"}
{"timestamp":"2016-07-07T12:06:40.327094+0000","level":"info","message":"subscribing to type=fanout, pipe=os:linux, funnel=client1-ubuntu-1404-0.25.3-1467893200"}
{"timestamp":"2016-07-07T12:06:40.327113+0000","level":"debug","message":"subscribing to a subscription","subscription":"all"}
{"timestamp":"2016-07-07T12:06:40.327197+0000","level":"info","message":"subscribing to type=fanout, pipe=all, funnel=client1-ubuntu-1404-0.25.3-1467893200"}
{"timestamp":"2016-07-07T12:06:40.327227+0000","level":"debug","message":"scheduling standalone checks"}
{"timestamp":"2016-07-07T12:06:42.115851+0000","level":"info","message":"received check request","check":{"client":"server1-ubuntu-1404","check":{"thresholds":{"warning":180,"critical":600},"name":"keepalive","issued":1467893201,"executed":1467893201,"output":"Keepalive sent from client 12 seconds ago","status":0},"signature":"7a2880f40a2f9457f660c9e31b58afb4"}}
{"timestamp":"2016-07-07T12:06:42.115973+0000","level":"debug","message":"processing check","check":{"client":"server1-ubuntu-1404","check":{"thresholds":{"warning":180,"critical":600},"name":"keepalive","issued":1467893201,"executed":1467893201,"output":"Keepalive sent from client 12 seconds ago","status":0},"signature":"7a2880f40a2f9457f660c9e31b58afb4"}}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:184:in `definition_exists?': undefined method `to_sym' for nil:NilClass (NoMethodError)
Did you mean?  to_s
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:62:in `block (2 levels) in create_category_methods'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:211:in `process_check_request'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:273:in `block (2 levels) in setup_subscriptions'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.2/lib/sensu/transport/snssqs.rb:95:in `block (3 levels) in subscribe'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.2/lib/sensu/transport/snssqs.rb:59:in `statsd_time'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.2/lib/sensu/transport/snssqs.rb:91:in `block (2 levels) in subscribe'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/iterator.rb:138:in `block in each'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/iterator.rb:231:in `block in spawn_workers'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `times'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `run_deferred_callbacks'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:18:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/exe/sensu-client:10:in `<top (required)>'
    from /opt/sensu/bin/sensu-client:22:in `load'
    from /opt/sensu/bin/sensu-client:22:in `<main>'


# client run 2
rm /var/log/sens/sensu-client.log
/etc/init.d/sensu-client start

root@ip-172-31-1-247:/var/log/sensu# tail -100 /var/log/sensu/sensu-client.log
{"timestamp":"2016-07-07T12:09:35.519950+0000","level":"warn","message":"loading config file","file":"/etc/sensu/config.json"}
{"timestamp":"2016-07-07T12:09:35.520048+0000","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d"}
{"timestamp":"2016-07-07T12:09:35.520085+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/snssqs.json"}
{"timestamp":"2016-07-07T12:09:35.520186+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/snssqs.json","changes":{"snssqs":[null,{"max_number_of_messages":10,"wait_time_seconds":2,"region":"eu-central-1","consuming_sqs_queue_url":"https://sqs.eu-central-1.amazonaws.com/001579709704/sensu-server","publishing_sns_topic_arn":"arn:aws:sns:eu-central-1:001579709704:sensu-client-1"}]}}
{"timestamp":"2016-07-07T12:09:35.520231+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/client.json"}
{"timestamp":"2016-07-07T12:09:35.520335+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/client.json","changes":{"client":[null,{"address":"52.59.48.159","subscriptions":["region:eu-central-1","provider:ec2","env:_default","os:linux","all"],"name":"client1-ubuntu-1404","signature":"f8022acc4947b319f27abb4216d16243","keepalive":{"thresholds":{"warning":180,"critical":600}},"ec2":{"ami_id":"ami-09618e66","instance_id":"i-0206a4235b6010ea8","instance_type":"t2.small","az":"eu-central-1b","profile":"default-hvm","region":"eu-central-1","tags":{"name":"user_test"}},"cloud":{"local_ipv4":"172.31.1.247","public_ipv4":"52.59.48.159","provider":"ec2"},"platform":"ubuntu","platform_version":"14.04","platform_family":"debian","chef":{"endpoint":"chefzero://localhost:8889","environment":"_default","client":"client1-ubuntu-1404","key":"/tmp/kitchen/client.pem"},"scheme_prefix":"sensu.default."}]}}
{"timestamp":"2016-07-07T12:09:35.526889+0000","level":"warn","message":"loading extension files from directory","directory":"/etc/sensu/extensions"}
{"timestamp":"2016-07-07T12:09:35.527103+0000","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
{"timestamp":"2016-07-07T12:09:35.527138+0000","level":"debug","message":"setting eventmachine threadpool size","size":22}
{"timestamp":"2016-07-07T12:09:35.549878+0000","level":"debug","message":"connecting to transport","name":"snssqs","settings":{"max_number_of_messages":10,"wait_time_seconds":2,"region":"eu-central-1","consuming_sqs_queue_url":"https://sqs.eu-central-1.amazonaws.com/001579709704/sensu-server","publishing_sns_topic_arn":"arn:aws:sns:eu-central-1:001579709704:sensu-client-1"}}
{"timestamp":"2016-07-07T12:09:35.777260+0000","level":"debug","message":"binding client tcp and udp sockets","options":{"bind":"127.0.0.1","port":3030}}
{"timestamp":"2016-07-07T12:09:35.777528+0000","level":"debug","message":"scheduling keepalives"}
{"timestamp":"2016-07-07T12:09:35.777672+0000","level":"debug","message":"publishing keepalive","payload":{"address":"52.59.48.159","subscriptions":["region:eu-central-1","provider:ec2","env:_default","os:linux","all"],"name":"client1-ubuntu-1404","signature":"f8022acc4947b319f27abb4216d16243","keepalive":{"thresholds":{"warning":180,"critical":600}},"ec2":{"ami_id":"ami-09618e66","instance_id":"i-0206a4235b6010ea8","instance_type":"t2.small","az":"eu-central-1b","profile":"default-hvm","region":"eu-central-1","tags":{"name":"user_test"}},"cloud":{"local_ipv4":"172.31.1.247","public_ipv4":"52.59.48.159","provider":"ec2"},"platform":"ubuntu","platform_version":"14.04","platform_family":"debian","chef":{"endpoint":"chefzero://localhost:8889","environment":"_default","client":"client1-ubuntu-1404","key":"/tmp/kitchen/client.pem"},"scheme_prefix":"sensu.default.","version":"0.25.3","timestamp":1467893375}}
{"timestamp":"2016-07-07T12:09:35.783634+0000","level":"debug","message":"subscribing to client subscriptions"}
{"timestamp":"2016-07-07T12:09:35.783675+0000","level":"debug","message":"subscribing to a subscription","subscription":"region:eu-central-1"}
{"timestamp":"2016-07-07T12:09:35.783734+0000","level":"info","message":"subscribing to type=fanout, pipe=region:eu-central-1, funnel=client1-ubuntu-1404-0.25.3-1467893375"}
{"timestamp":"2016-07-07T12:09:35.783775+0000","level":"debug","message":"subscribing to a subscription","subscription":"provider:ec2"}
{"timestamp":"2016-07-07T12:09:35.783820+0000","level":"info","message":"subscribing to type=fanout, pipe=provider:ec2, funnel=client1-ubuntu-1404-0.25.3-1467893375"}
{"timestamp":"2016-07-07T12:09:35.783843+0000","level":"debug","message":"subscribing to a subscription","subscription":"env:_default"}
{"timestamp":"2016-07-07T12:09:35.783871+0000","level":"info","message":"subscribing to type=fanout, pipe=env:_default, funnel=client1-ubuntu-1404-0.25.3-1467893375"}
{"timestamp":"2016-07-07T12:09:35.783893+0000","level":"debug","message":"subscribing to a subscription","subscription":"os:linux"}
{"timestamp":"2016-07-07T12:09:35.783921+0000","level":"info","message":"subscribing to type=fanout, pipe=os:linux, funnel=client1-ubuntu-1404-0.25.3-1467893375"}
{"timestamp":"2016-07-07T12:09:35.783942+0000","level":"debug","message":"subscribing to a subscription","subscription":"all"}
{"timestamp":"2016-07-07T12:09:35.784008+0000","level":"info","message":"subscribing to type=fanout, pipe=all, funnel=client1-ubuntu-1404-0.25.3-1467893375"}
{"timestamp":"2016-07-07T12:09:35.784036+0000","level":"debug","message":"scheduling standalone checks"}
{"timestamp":"2016-07-07T12:09:39.231286+0000","level":"info","message":"received check request","check":{"client":"server1-ubuntu-1404","check":{"command":"check-elb-health-sdk.rb -r eu-central-1 -n TestCDN-CdnAsyEl-1UQE4U0G0U49G","standalone":true,"handlers":["default"],"interval":60,"occurrences":5,"source":"TestCDN-CdnAsyEl-1UQE4U0G0U49G","name":"elb_TestCDN-CdnAsyEl-1UQE4U0G0U49G","issued":1467893106,"executed":1467893106,"duration":2.571,"output":"ELBHealth OK: TestCDN-CdnAsyEl-1UQE4U0G0U49G => healthy. \n","status":0},"signature":"7a2880f40a2f9457f660c9e31b58afb4"}}
{"timestamp":"2016-07-07T12:09:39.231449+0000","level":"debug","message":"processing check","check":{"client":"server1-ubuntu-1404","check":{"command":"check-elb-health-sdk.rb -r eu-central-1 -n TestCDN-CdnAsyEl-1UQE4U0G0U49G","standalone":true,"handlers":["default"],"interval":60,"occurrences":5,"source":"TestCDN-CdnAsyEl-1UQE4U0G0U49G","name":"elb_TestCDN-CdnAsyEl-1UQE4U0G0U49G","issued":1467893106,"executed":1467893106,"duration":2.571,"output":"ELBHealth OK: TestCDN-CdnAsyEl-1UQE4U0G0U49G => healthy. \n","status":0},"signature":"7a2880f40a2f9457f660c9e31b58afb4"}}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:184:in `definition_exists?': undefined method `to_sym' for nil:NilClass (NoMethodError)
Did you mean?  to_s
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:62:in `block (2 levels) in create_category_methods'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:211:in `process_check_request'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:273:in `block (2 levels) in setup_subscriptions'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.2/lib/sensu/transport/snssqs.rb:95:in `block (3 levels) in subscribe'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.2/lib/sensu/transport/snssqs.rb:59:in `statsd_time'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-snssqs-2.0.2/lib/sensu/transport/snssqs.rb:91:in `block (2 levels) in subscribe'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/iterator.rb:138:in `block in each'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/iterator.rb:231:in `block in spawn_workers'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `times'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `run_deferred_callbacks'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:18:in `run'
    from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/exe/sensu-client:10:in `<top (required)>'
    from /opt/sensu/bin/sensu-client:22:in `load'
    from /opt/sensu/bin/sensu-client:22:in `<main>'

```

As  you can see in the second example the client1-ubuntu-1404 receives checks which belong to server1-ubuntu-1404.

This is the minimal client config:

```
root@ip-172-31-1-247:/etc/sensu# find
.
./conf.d
./conf.d/snssqs.json
./conf.d/checks
./conf.d/client.json
./extensions
./handlers
./mutators
./plugins
./config.json
root@ip-172-31-1-247:/etc/sensu# cat */*
cat: conf.d/checks: Is a directory
{
  "client": {
    "address": "52.59.48.159",
    "subscriptions": [
      "region:eu-central-1",
      "provider:ec2",
      "env:_default",
      "os:linux",
      "all"
    ],
    "name": "client1-ubuntu-1404",
    "signature": "f8022acc4947b319f27abb4216d16243",
    "keepalive": {
      "thresholds": {
        "warning": 180,
        "critical": 600
      }
    },
    "ec2": {
      "ami_id": "ami-09618e66",
      "instance_id": "i-0206a4235b6010ea8",
      "instance_type": "t2.small",
      "az": "eu-central-1b",
      "profile": "default-hvm",
      "region": "eu-central-1",
      "tags": {
        "name": "user_test"
      }
    },
    "cloud": {
      "local_ipv4": "172.31.1.247",
      "public_ipv4": "52.59.48.159",
      "provider": "ec2"
    },
    "platform": "ubuntu",
    "platform_version": "14.04",
    "platform_family": "debian",
    "chef": {
      "endpoint": "chefzero://localhost:8889",
      "environment": "_default",
      "client": "client1-ubuntu-1404",
      "key": "/tmp/kitchen/client.pem"
    },
    "scheme_prefix": "sensu.default."
  }
}
{
  "snssqs": {
    "max_number_of_messages": 10,
    "wait_time_seconds": 2,
    "region": "eu-central-1",
    "consuming_sqs_queue_url": "https://sqs.eu-central-1.amazonaws.com/001579709704/sensu-server",
    "publishing_sns_topic_arn": "arn:aws:sns:eu-central-1:001579709704:sensu-client-1"
  }
}

```

**Comment by tomwans** [comment]
So the only time that a subscribe would be triggered is if there are any subscription-based checks (https://github.com/sensu/sensu/blob/394fbc855eecce39f3072bf7d7b8ef9ba0aa433a/lib/sensu/client/process.rb#L269). This transport doesn't work with subscription-based checks. It's possible that you have a check somewhere that isn't standalone, causing the client to try to consume from the queue.

**Comment by runningman84** [comment]
There are no subscription based checks as you can see in my configuration above.

Can you modify the transport in a way that the client do not need not know any sqs configuration settings? 

Can you modify the transport that in case of a client no real queue connection is made?

**Comment by runningman84** [comment]
I suppose the problem is that my clients have configured subscriptions. We do have them to group them in uchiwa. But they do not receive anything because we have only standalone checks. 

Are you able to find out whether your transport is running in a client or a server? In this case you could just ensure that the client does not connect to the queue and the subscribe function would be an empty dummy.

**Comment by runningman84** [comment]
Ok I made some modification to handle client and server transports differently:
https://github.com/runningman84/sensu-transport-snssqs/commit/56c45187a8f9dd1e4bc158d92b90865d15275942

It looks like it works fine and the clients do not speak with sqs anymore (they also do not need any sqs settings). The server only speaks with sqs and does not need a sns client.

But I think I messed up some EM stuff, my client has about 100% cpu usage (it works fine altough),

Can you take a look at it?

**Comment by runningman84** [comment]
In the next release of sensu the snssqs transport will not work anymore:
https://github.com/sensu/sensu-settings/pull/40#issuecomment-237315758

**Comment by portertech** [comment]
I believe the SQS transport only needs to no-op subscribe() when the pipe type is fanout.

**Comment by tomwans** [comment]
This should be fixed by https://github.com/SimpleFinance/sensu-transport-snssqs/issues/8, please re-open if not.
